-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 10:51:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartvacinas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartvacinas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartvacinas` DEFAULT CHARACTER SET utf8 ;
USE `smartvacinas` ;

-- -----------------------------------------------------
-- Table `smartvacinas`.`campanha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartvacinas`.`campanha` ;

CREATE TABLE IF NOT EXISTS `smartvacinas`.`campanha` (
  `idcampanha` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idcampanha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartvacinas`.`vacina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartvacinas`.`vacina` ;

CREATE TABLE IF NOT EXISTS `smartvacinas`.`vacina` (
  `idvacina` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idvacina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartvacinas`.`campanha_vacina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartvacinas`.`campanha_vacina` ;

CREATE TABLE IF NOT EXISTS `smartvacinas`.`campanha_vacina` (
  `vacina_idvacina` INT UNSIGNED NOT NULL,
  `campanha_idcampanha` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`vacina_idvacina`, `campanha_idcampanha`),
  INDEX `fk_vacina_has_campanha_campanha1_idx` (`campanha_idcampanha` ASC) VISIBLE,
  INDEX `fk_vacina_has_campanha_vacina_idx` (`vacina_idvacina` ASC) VISIBLE,
  CONSTRAINT `fk_vacina_has_campanha_vacina`
    FOREIGN KEY (`vacina_idvacina`)
    REFERENCES `smartvacinas`.`vacina` (`idvacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacina_has_campanha_campanha1`
    FOREIGN KEY (`campanha_idcampanha`)
    REFERENCES `smartvacinas`.`campanha` (`idcampanha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
